version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run: brew install swiftlint
      - run: swiftlint lint --reporter junit | tee lintResult.xml
      - run: swift test | tee testResults.xml
      - run: swift build
      - store_artifacts:
          path: 
            - lintResult.xml
            - testResults.xml
      - store_test_results:
          path: 
            - lintResult.xml
            - testResults.xml


    
workflows:
  build-and-test-wf:
    jobs:
      - build-and-test
